# Generated by Django 5.0.14 on 2025-12-16 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Distrito 12, Comisión A, Grupo 3', max_length=100, verbose_name='Nombre del Distrito')),
                ('code', models.CharField(help_text='Código único del distrito (D01, D02, COM-A, etc.)', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del distrito (especialidad, característica, etc.)', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si el distrito está activo', verbose_name='Activo')),
                ('color_primary', models.CharField(default='#d4af37', help_text='Color hex para representación visual (#RRGGBB)', max_length=7, verbose_name='Color Primario')),
                ('color_secondary', models.CharField(default='#c0c0c0', help_text='Color secundario para UI', max_length=7, verbose_name='Color Secundario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: 2025 - Primer Semestre, 75° Hunger Games', max_length=100, verbose_name='Nombre de la Temporada')),
                ('code', models.CharField(help_text='Código único (2025-1, HG75, etc.)', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=False, help_text='Solo una temporada puede estar activa a la vez', verbose_name='Temporada Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DistrictMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('left_at', models.DateTimeField(blank=True, help_text='Si está vacío, está activo en el distrito', null=True, verbose_name='Fecha de Salida')),
                ('is_active', models.BooleanField(default=True, help_text='Si la membresía está activa', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la asignación o cambio de distrito', verbose_name='Notas')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='districts.district', verbose_name='Distrito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Personaje')),
            ],
            options={
                'verbose_name': 'Membresía de Distrito',
                'verbose_name_plural': 'Membresías de Distrito',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='districts_d_user_id_9d5e56_idx'), models.Index(fields=['district', 'is_active'], name='districts_d_distric_35146d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeasonDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participating', models.BooleanField(default=True, help_text='Si el distrito participa en esta temporada', verbose_name='Participa')),
                ('total_points', models.IntegerField(default=0, help_text='Puntos acumulados del distrito en esta temporada', verbose_name='Puntos Totales')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='districts.district', verbose_name='Distrito')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='districts.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Distrito en Temporada',
                'verbose_name_plural': 'Distritos en Temporada',
                'ordering': ['-total_points'],
                'unique_together': {('season', 'district')},
            },
        ),
    ]
