# Generated by Django 5.0.14 on 2025-12-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Unidad Académica')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(help_text='Identificador único de la unidad', max_length=50, unique=True, verbose_name='Código de Unidad')),
                ('es_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad Académica',
                'verbose_name_plural': 'Unidades Académicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Torneo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_edicion', models.IntegerField(help_text='Ej: 75 para "75 Hunger Games"', verbose_name='Número de Edición')),
                ('fecha_acreditacion_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del período de acreditación', verbose_name='Inicio Acreditación')),
                ('fecha_acreditacion_fin', models.DateTimeField(help_text='Fecha y hora de fin del período de acreditación', verbose_name='Fin Acreditación')),
                ('fecha_competencia_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la competencia', verbose_name='Inicio Competencia')),
                ('fecha_competencia_fin', models.DateTimeField(help_text='Fecha y hora de fin de la competencia', verbose_name='Fin Competencia')),
                ('fecha_premios', models.DateTimeField(help_text='Fecha y hora de entrega de premios', verbose_name='Entrega de Premios')),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('acreditacion', 'Período de Acreditación'), ('competencia', 'En Competencia'), ('entrega_premios', 'Entrega de Premios'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20, verbose_name='Estado del Torneo')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Torneo Activo')),
                ('permite_equipos', models.BooleanField(default=False, verbose_name='Permite Competencia por Equipos')),
                ('puntuacion_por_unidad', models.BooleanField(default=True, help_text='Los puntos se suman a la unidad académica', verbose_name='Puntuación por Unidad Académica')),
                ('puntos_minimos_ganar', models.IntegerField(default=0, help_text='Puntos mínimos requeridos para ganar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tournaments/imagenes/', verbose_name='Imagen del Torneo')),
                ('creado_por', models.ForeignKey(limit_choices_to={'rol': 'jefe_capitolio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('planificacion', 'En Planificación'), ('acreditacion', 'Período de Acreditación'), ('competencia', 'En Competencia'), ('entrega_premios', 'Entrega de Premios'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('planificacion', 'En Planificación'), ('acreditacion', 'Período de Acreditación'), ('competencia', 'En Competencia'), ('entrega_premios', 'Entrega de Premios'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField(blank=True, null=True, verbose_name='Razón del cambio')),
                ('cambio_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambio realizado por')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estado', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Cambio de Estado de Torneo',
                'verbose_name_plural': 'Cambios de Estado de Torneo',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='TournamentVigilante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_torneo', models.CharField(choices=[('general', 'Vigilante General'), ('acreditacion', 'Vigilante de Acreditación'), ('competencia', 'Vigilante de Competencia'), ('premios', 'Vigilante de Entrega de Premios')], default='general', max_length=20, verbose_name='Rol en el Torneo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(limit_choices_to={'rol': 'jefe_capitolio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_vigilantes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigilantes_asignados', to='tournaments.tournament', verbose_name='Torneo')),
                ('vigilante', models.ForeignKey(limit_choices_to={'rol': 'vigilante'}, on_delete=django.db.models.deletion.CASCADE, related_name='torneos_vigilancia', to=settings.AUTH_USER_MODEL, verbose_name='Vigilante')),
            ],
            options={
                'verbose_name': 'Vigilante de Torneo',
                'verbose_name_plural': 'Vigilantes de Torneo',
                'ordering': ['torneo', 'rol_en_torneo'],
                'unique_together': {('torneo', 'vigilante')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(limit_choices_to={'rol': 'jefe_capitolio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_mentores_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('mentor', models.ForeignKey(limit_choices_to={'rol': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='torneos_mentoreo', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentores_asignados', to='tournaments.tournament', verbose_name='Torneo')),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentores_torneo', to='tournaments.unidadacademica', verbose_name='Unidad Académica')),
            ],
            options={
                'verbose_name': 'Mentor de Torneo',
                'verbose_name_plural': 'Mentores de Torneo',
                'ordering': ['torneo', 'unidad_academica'],
                'unique_together': {('torneo', 'unidad_academica')},
            },
        ),
    ]
