# Generated by Django 5.0.14 on 2025-12-16 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        # Primero remover la restricción unique_together antigua
        migrations.AlterUniqueTogether(
            name='tournamentmentor',
            unique_together=set(),
        ),
        # Remover el campo viejo
        migrations.RemoveField(
            model_name='tournamentmentor',
            name='unidad_academica',
        ),
        # Agregar el nuevo campo
        migrations.AddField(
            model_name='tournamentmentor',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentores_torneo', to='districts.district', verbose_name='Distrito'),
        ),
        # Ahora establecer la nueva restricción unique_together
        migrations.AlterUniqueTogether(
            name='tournamentmentor',
            unique_together={('torneo', 'distrito')},
        ),
        # Finalmente alterar las opciones del modelo
        migrations.AlterModelOptions(
            name='tournamentmentor',
            options={'ordering': ['torneo', 'distrito'], 'verbose_name': 'Mentor de Torneo', 'verbose_name_plural': 'Mentores de Torneo'},
        ),
        # Borrar el modelo UnidadAcademica
        migrations.DeleteModel(
            name='UnidadAcademica',
        ),
    ]
