# Generated by Django 5.0.14 on 2025-12-15 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0004_reto_limite_memoria_reto_limite_tiempo_and_more'),
        ('capitol', '0002_personaje_distrito_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript')], max_length=20, verbose_name='Lenguaje de Programación')),
                ('codigo', models.TextField(help_text='Código enviado por el tributo', verbose_name='Código Fuente')),
                ('veredicto', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('SE', 'System Error'), ('PE', 'Pending')], default='PE', max_length=3, verbose_name='Veredicto')),
                ('puntos_obtenidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntos Obtenidos')),
                ('casos_pasados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casos de Prueba Pasados')),
                ('casos_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casos de Prueba Totales')),
                ('tiempo_ejecucion', models.FloatField(blank=True, help_text='Tiempo total de ejecución de todos los tests', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Ejecución (segundos)')),
                ('memoria_usada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Memoria Usada (MB)')),
                ('stdout', models.TextField(blank=True, help_text='Output del programa (stdout)', verbose_name='Salida Estándar')),
                ('stderr', models.TextField(blank=True, help_text='Errores del programa (stderr)', verbose_name='Salida de Error')),
                ('detalles_ejecucion', models.JSONField(blank=True, default=dict, help_text='Resultados detallados de cada caso de prueba (no visible para tributos)', verbose_name='Detalles de Ejecución')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Evaluación')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='arena.reto', verbose_name='Reto')),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='capitol.tributoinfo', verbose_name='Tributo')),
            ],
            options={
                'verbose_name': 'Entrega de Código',
                'verbose_name_plural': 'Entregas de Código',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['tributo', 'reto'], name='judge_submi_tributo_42fe17_idx'), models.Index(fields=['veredicto'], name='judge_submi_veredic_b25f67_idx'), models.Index(fields=['fecha_envio'], name='judge_submi_fecha_e_7eaa1f_idx')],
            },
        ),
    ]
