# Generated by Django 5.0.14 on 2025-12-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('PASSED', 'Pasado'), ('FAILED', 'Fallido'), ('TIMEOUT', 'Tiempo Excedido'), ('MEMORY_ERROR', 'Error de Memoria'), ('RUNTIME_ERROR', 'Error de Ejecución'), ('ERROR', 'Error del Sistema')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('passed', models.BooleanField(default=False, verbose_name='Pasado')),
                ('actual_output', models.TextField(blank=True, help_text='Output generado por el código del tributo', verbose_name='Salida Real')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de Ejecución (segundos)')),
                ('memory_used', models.IntegerField(blank=True, null=True, verbose_name='Memoria Usada (MB)')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el test falló', verbose_name='Mensaje de Error')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ejecutado en')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='judge.submission', verbose_name='Entrega')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='challenges.testcase', verbose_name='Caso de Prueba')),
            ],
            options={
                'verbose_name': 'Resultado de Test Case',
                'verbose_name_plural': 'Resultados de Test Cases',
                'ordering': ['submission', 'test_case__order'],
                'unique_together': {('submission', 'test_case')},
            },
        ),
    ]
