# Generated by Django 5.0.14 on 2025-12-09 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capitol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Reto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Problema')),
                ('enunciado', models.TextField(help_text='Descripción detallada del problema', verbose_name='Enunciado Completo')),
                ('dificultad', models.CharField(choices=[('novato', 'Novato'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='novato', max_length=15)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('equipo', 'Por Equipo'), ('distrito', 'Por Distrito')], default='individual', max_length=15)),
                ('categoria', models.CharField(blank=True, help_text='Ej: Algoritmos, Estructuras de Datos, etc.', max_length=100, null=True)),
                ('puntos_base', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('puntos_bonus', models.IntegerField(default=0, help_text='Puntos extra por completar rápido', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de Publicación')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('is_activo', models.BooleanField(default=True, verbose_name='Reto Activo')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para Tributos')),
                ('tiene_validacion_automatica', models.BooleanField(default=False)),
                ('lenguajes_permitidos', models.CharField(default='python,java,cpp,javascript', help_text='Lenguajes permitidos separados por comas', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_datos', models.FileField(blank=True, help_text='Archivos de datos de prueba', null=True, upload_to='retos/datos/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reto',
                'verbose_name_plural': 'Retos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='CasoDePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Caso')),
                ('entrada', models.TextField(verbose_name='Entrada/Input')),
                ('salida_esperada', models.TextField(verbose_name='Salida Esperada/Output')),
                ('is_visible', models.BooleanField(default=True, help_text='Visible para los tributos (ejemplos)')),
                ('es_ejemplo', models.BooleanField(default=False, help_text='Es un caso de ejemplo en el enunciado')),
                ('puntos', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('orden', models.IntegerField(default=0, help_text='Orden de ejecución')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='arena.reto')),
            ],
            options={
                'verbose_name': 'Caso de Prueba',
                'verbose_name_plural': 'Casos de Prueba',
                'ordering': ['reto', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Torneo')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edicion', models.IntegerField(help_text='Ej: 75 para "75th Hunger Games"', verbose_name='Número de Edición')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Finalización')),
                ('fecha_inscripcion_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Inscripciones')),
                ('fecha_inscripcion_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Inscripciones')),
                ('estado', models.CharField(choices=[('configuracion', 'En Configuración'), ('inscripcion', 'Inscripción Abierta'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='configuracion', max_length=20)),
                ('is_activo', models.BooleanField(default=True, verbose_name='Torneo Activo')),
                ('puntos_minimos_ganar', models.IntegerField(default=0, help_text='Puntos mínimos para ganar')),
                ('permite_equipos', models.BooleanField(default=False, help_text='Permite competencia por equipos')),
                ('puntuacion_por_distrito', models.BooleanField(default=True, help_text='Los puntos suman al distrito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='torneos/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='reto',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='arena.torneo'),
        ),
        migrations.CreateModel(
            name='ParticipacionTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('enviado', 'Enviado'), ('validando', 'En Validación'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('tiempo_agotado', 'Tiempo Agotado')], default='no_iniciado', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('lenguaje', models.CharField(blank=True, help_text='Lenguaje de programación usado', max_length=50, null=True)),
                ('codigo_solucion', models.TextField(blank=True, null=True, verbose_name='Código de la Solución')),
                ('puntos_obtenidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('casos_pasados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('casos_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_ejecucion', models.FloatField(blank=True, help_text='Tiempo en segundos', null=True)),
                ('output_validacion', models.TextField(blank=True, help_text='Resultado de la validación', null=True)),
                ('comentarios_mentor', models.TextField(blank=True, null=True)),
                ('numero_intento', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='capitol.tributoinfo')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='arena.reto')),
            ],
            options={
                'verbose_name': 'Participación en Reto',
                'verbose_name_plural': 'Participaciones en Retos',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('tributo', 'reto', 'numero_intento')},
            },
        ),
        migrations.CreateModel(
            name='RankingDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('puntos_totales', models.IntegerField(default=0)),
                ('retos_completados', models.IntegerField(default=0)),
                ('tributos_activos', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_distrito', to='arena.torneo')),
            ],
            options={
                'verbose_name': 'Ranking de Distrito',
                'verbose_name_plural': 'Rankings de Distritos',
                'ordering': ['-puntos_totales'],
                'unique_together': {('torneo', 'distrito')},
            },
        ),
        migrations.CreateModel(
            name='MentorDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Número de Distrito')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(limit_choices_to={'rol': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='distritos_asignados', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mentores', to='arena.torneo')),
            ],
            options={
                'verbose_name': 'Asignación de Mentor',
                'verbose_name_plural': 'Asignaciones de Mentores',
                'ordering': ['torneo', 'distrito'],
                'unique_together': {('distrito', 'torneo'), ('mentor', 'torneo')},
            },
        ),
    ]
