# Generated by Django 5.0.14 on 2025-12-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
        ('capitol', '0002_personaje_distrito_asignado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='vigilantes_asignados',
            field=models.ManyToManyField(blank=True, help_text='Vigilantes (Peacekeepers) que supervisan este torneo', limit_choices_to={'rol': 'vigilante'}, related_name='torneos_vigilados', to=settings.AUTH_USER_MODEL, verbose_name='Vigilantes Asignados'),
        ),
        migrations.CreateModel(
            name='AyudaMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pista', '💡 Pista'), ('ejemplo', '📝 Ejemplo de Código'), ('recurso', '📚 Recurso de Aprendizaje'), ('motivacion', '💪 Mensaje de Motivación'), ('advertencia', '⚠️ Advertencia/Alerta')], default='pista', max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Ayuda')),
                ('contenido', models.TextField(verbose_name='Contenido de la Ayuda')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leída por el tributo?')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('costo_puntos', models.IntegerField(default=0, help_text='Puntos que costó enviar esta ayuda (para sistema de patrocinio)')),
                ('mentor', models.ForeignKey(limit_choices_to={'rol': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ayudas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(blank=True, help_text='Reto específico al que se refiere la ayuda (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ayudas_relacionadas', to='arena.reto')),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudas_recibidas', to='capitol.tributoinfo', verbose_name='Tributo Destinatario')),
            ],
            options={
                'verbose_name': 'Ayuda de Mentor',
                'verbose_name_plural': 'Ayudas de Mentores',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
