# Generated by Django 5.0.14 on 2025-12-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_torneo_vigilantes_asignados_ayudamentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=1000, help_text='Puntos totales asignados al mentor')),
                ('puntos_usados', models.IntegerField(default=0, help_text='Puntos gastados en ayudas')),
                ('max_ayudas_por_dia', models.IntegerField(default=10, help_text='Número máximo de ayudas que puede enviar por día')),
                ('total_ayudas_enviadas', models.IntegerField(default=0)),
                ('ultima_ayuda_enviada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(limit_choices_to={'rol': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_patrocinio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto de Mentor',
                'verbose_name_plural': 'Presupuestos de Mentores',
            },
        ),
    ]
