# Generated by Django 5.0.14 on 2025-12-15 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_presupuestomentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='limite_memoria',
            field=models.IntegerField(default=256, help_text='Memoria máxima permitida para la ejecución', validators=[django.core.validators.MinValueValidator(64)], verbose_name='Límite de Memoria (MB)'),
        ),
        migrations.AddField(
            model_name='reto',
            name='limite_tiempo',
            field=models.FloatField(default=5.0, help_text='Tiempo máximo de ejecución por test', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Límite de Tiempo (segundos)'),
        ),
        migrations.AddField(
            model_name='reto',
            name='tests_ocultos',
            field=models.JSONField(blank=True, default=dict, help_text='Tests por lenguaje. Formato: {"python": [...], "java": [...], "javascript": [...]}', verbose_name='Tests Ocultos'),
        ),
    ]
