# Generated by Django 5.0.14 on 2025-12-10 00:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='distrito_asignado',
            field=models.IntegerField(blank=True, help_text='Distrito asignado al mentor (1-13)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddField(
            model_name='personaje',
            name='unidad_academica',
            field=models.CharField(blank=True, help_text='Unidad Académica/Sede UNPA que representa (solo para mentores)', max_length=200, null=True, verbose_name='Unidad Académica'),
        ),
        migrations.AddField(
            model_name='tributoinfo',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='Mentor que representa al tributo (su "Haymitch")', limit_choices_to={'rol': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tributos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Mentor Asignado'),
        ),
    ]
