# Generated by Django 5.0.14 on 2025-12-16 02:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(help_text='Descripción general del problema', verbose_name='Descripción')),
                ('statement', models.TextField(help_text='Enunciado detallado con ejemplos y explicaciones', verbose_name='Enunciado Completo')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil'), ('expert', 'Experto')], default='easy', max_length=10, verbose_name='Dificultad')),
                ('category', models.CharField(blank=True, help_text='Ej: Algoritmos, Estructuras de Datos, Matemáticas, etc.', max_length=100, verbose_name='Categoría')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para filtrado: ["arrays", "recursion", "dynamic-programming"]', verbose_name='Etiquetas')),
                ('time_limit', models.PositiveIntegerField(default=1, help_text='Tiempo máximo de ejecución por caso de prueba', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Límite de Tiempo (segundos)')),
                ('memory_limit', models.PositiveIntegerField(default=128, help_text='Memoria máxima permitida', validators=[django.core.validators.MinValueValidator(64)], verbose_name='Límite de Memoria (MB)')),
                ('allowed_languages', models.JSONField(default=list, help_text='Lista de lenguajes: ["python", "java", "javascript", "cpp"]', verbose_name='Lenguajes Permitidos')),
                ('base_points', models.PositiveIntegerField(default=100, verbose_name='Puntos Base')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo y disponible para usar', verbose_name='Activo')),
                ('is_public', models.BooleanField(default=False, help_text='Si es visible públicamente o solo en torneos específicos', verbose_name='Público')),
                ('input_format_description', models.TextField(blank=True, help_text='Descripción del formato de entrada esperado', verbose_name='Formato de Entrada')),
                ('output_format_description', models.TextField(blank=True, help_text='Descripción del formato de salida esperado', verbose_name='Formato de Salida')),
                ('constraints', models.TextField(blank=True, help_text='Restricciones del problema (rangos de valores, etc.)', verbose_name='Restricciones')),
                ('code_templates', models.JSONField(blank=True, default=dict, help_text='Código inicial por lenguaje: {"python": "def solve():\\n    pass", ...}', verbose_name='Plantillas de Código')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Datos de entrada para el test', verbose_name='Entrada')),
                ('expected_output', models.TextField(help_text='Salida correcta esperada', verbose_name='Salida Esperada')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo del caso de prueba', max_length=100, verbose_name='Nombre del Test')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de qué prueba este caso', verbose_name='Descripción')),
                ('is_visible', models.BooleanField(default=False, help_text='Si el tributo puede ver este test case (test de ejemplo)', verbose_name='Visible')),
                ('is_sample', models.BooleanField(default=False, help_text='Si es un caso de ejemplo mostrado en el enunciado', verbose_name='Es Ejemplo')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Peso del test case para el cálculo de puntuación', verbose_name='Peso')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de ejecución del test', verbose_name='Orden')),
                ('custom_time_limit', models.PositiveIntegerField(blank=True, help_text='Si se especifica, sobrescribe el límite del challenge', null=True, verbose_name='Límite de Tiempo Personalizado (segundos)')),
                ('custom_memory_limit', models.PositiveIntegerField(blank=True, help_text='Si se especifica, sobrescribe el límite del challenge', null=True, verbose_name='Límite de Memoria Personalizado (MB)')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='challenges.challenge', verbose_name='Challenge')),
            ],
            options={
                'verbose_name': 'Caso de Prueba',
                'verbose_name_plural': 'Casos de Prueba',
                'ordering': ['challenge', 'order', 'id'],
                'unique_together': {('challenge', 'order')},
            },
        ),
    ]
